server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://devxavierr:pvyCTrYVIX3IGBsa@cluster0.ru7apti.mongodb.net/myFirstDatabase?retryWrites=true&w=majority}
      auto-index-creation: true

